### ISSUE TITLE
Linux Ubuntu 18.04 - SIGSEV in MultiPlayerManager::Update()

### ISSUE THREAD

**Issue by shadoxx** [janusvr/janus#3]
```
#0  0x0000555555649941 in MultiPlayerManager::Update(QPointer<Player>, QString const&, QList<QString>, QString const&, bool) (this=this@entry=0x555556b80a40, player=..., url=..., adjacent_urls=..., name=..., room_allows_party_mode=room_allows_party_mode@entry=true) at multiplayermanager.cpp:291
        send_updates = <optimized out>
        update_time_secs = <optimized out>
        players_to_remove = Python Exception <class 'gdb.MemoryError'> Cannot access memory at address 0x7fffff7fec20:
#1  0x00005555555dcce1 in Game::UpdateMultiplayer() (this=this@entry=0x555556b28bd0) at game.cpp:5608
        room_name = {static null = {<No data fields>}, d = 0x7fffcc10fa60}
        adjacent_urls =
            {<QListSpecialMethods<QString>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, <No data fields>}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7fffea8b7700 <QListData::shared_null>}, d = 0x7fffea8b7700 <QListData::shared_null>}}
        visible_rooms =
            {<QListSpecialMethods<QPointer<Room> >> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, <No data fields>}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7ffefc324e70}, d = 0x7ffefc324e70}}
        g = {wp = {d = 0x555556ae8220, value = 0x555556b86f40}}
        room_url = {static null = {<No data fields>}, d = 0x555567c628b0}
        room_allows_party_mode = <optimized out>
        room_url_no_anchor = {static null = {<No data fields>}, d = 0x555567c628b0}
        r = {wp = {d = 0x555567c90a10, value = 0x5555589e0b00}}
#2  0x00005555555f6207 in Game::Update() (this=0x555556b28bd0) at game.cpp:370
        r = {wp = {d = 0x555567c90a10, value = 0x5555589e0b00}}
        r0 = {wp = {d = 0x7fffff8f30d8, value = 0x555556a366c0}}
        r1 = {wp = {d = 0x55555dc55a30, value = 0x5555555fbc43 <Player::SetF(char const*, float)+131>}}
#3  0x0000555555793849 in GLWidget::paintGL() (this=0x555555d70920) at glwidget.cpp:649
        delta_t = 0.214
        r = {wp = {d = 0x3f0000003f000000, value = 0x0}}
        w2 = <optimized out>
        h2 = <optimized out>
        near_dist = <optimized out>
        far_dist = <optimized out>
        mouse_pos = <optimized out>
        s = <optimized out>
        base_xform =
          {m = {{3.39338655e+13, 3.0611365e-41, 3.50154025e+13, 4.59163468e-41}, {3.39338655e+13, 3.0611365e-41, 3.37432428e+13, 3.0611365e-41}, {5.60519386e-45, 0, 3.49363734e+13, 4.59163468e-41}, {0, 1.52461273e-42, 0, 8.18358303e-43}}, flagBits = 0}
        dpr = <optimized out>
        overrideWidth = <optimized out>
        overrideHeight = <optimized out>
        disp_mode_override = <optimized out>
#4  0x00007fffec00285d in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007fffebfe2038 in QWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007fffebfa382c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
```

**Comment by shadoxx** [comment]
Marking as closed. Issue no longer experienced.
